### ISSUE TITLE
Username text not visible in search dropdown

### ISSUE THREAD

**Issue by iamdarkle** [flarum/framework#3681]
### Current Behavior

I noticed when upgrading to 1.6 today and from what I see on discuss it also happens, with the upgrade the username text is not visible in the search dropdown, as when trying to inspect the item in the search dropdown it closes automatically, I haven't managed to see exactly if it's a problem with the color or something.

Bit of a random question but is there a trick to leave the search dropdown open for inspecting in it? 😂

### Steps to Reproduce

1. Search for a user name in the forum search.

### Expected Behavior

Show the text corresponding to the username.

### Environment

- Flarum version: 1.6.0

**Comment by davwheat** [comment]
@imorland Maybe this is related to the mentions issue you saw?

**Comment by imorland** [comment]
Yep, it absolutely is.. This can be closed when `1.6.1` is released

**Comment by iamdarkle** [comment]
Yeah fixed with `1.6.1` 👍

**Comment by SychO9** [comment]
Actually I'd rather keep this open because we technically did not fix the issue which occurs when we update JS dependencies. We just reverted that for 1.6

Now we need to update JS dependencies and figure out the problem. In a separate PR.
